import { useState, useEffect } from 'react';
const API = import.meta.env.VITE_API_URL || '';
export default function App() {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => {
    fetch(API + '/api/health').then(r => r.json()).then(setData).catch(e => setError(e.message));
  }, []);
  return (
    <div style={{minHeight:'100vh',background:'#0f172a',color:'#f1f5f9',fontFamily:'system-ui,sans-serif',padding:'40px 20px'}}>
      <div style={{maxWidth:800,margin:'0 auto'}}>
        <div style={{textAlign:'center',marginBottom:40}}>
          <div style={{fontSize:48,marginBottom:16}}>🚀</div>
          <h1 style={{fontSize:32,fontWeight:800,margin:'0 0 8px',background:'linear-gradient(135deg,#60a5fa,#a78bfa)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>movie tickets selling applicat</h1>
          <p style={{color:'#94a3b8',fontSize:16}}>Generated by AI App Generator</p>
        </div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:16,marginBottom:32}}>
          {[['⚛️','React Frontend','Running on port 80'],['🟢','Node.js Backend','Running on port 3000'],['🐘','PostgreSQL','Database ready'],['🐳','Docker','All services up']].map(([icon,title,desc])=>(
            <div key={title} style={{background:'#1e293b',borderRadius:12,padding:20,border:'1px solid #334155'}}>
              <div style={{fontSize:28,marginBottom:8}}>{icon}</div>
              <div style={{fontWeight:700,marginBottom:4}}>{title}</div>
              <div style={{color:'#64748b',fontSize:13}}>{desc}</div>
            </div>
          ))}
        </div>
        <div style={{background:'#1e293b',borderRadius:12,padding:24,border:'1px solid #334155'}}>
          <h2 style={{margin:'0 0 16px',fontSize:18}}>Backend Status</h2>
          {error ? <p style={{color:'#f87171'}}>Backend not reachable: {error}</p> : data ? <p style={{color:'#4ade80'}}>✅ Backend is running</p> : <p style={{color:'#94a3b8'}}>Connecting...</p>}
        </div>
      </div>
    </div>
  );
}